### ISSUE TITLE
Missing module @gerrit0/typedoc

### ISSUE THREAD

**Issue by Floppy012** [google/typedoc-neo-theme#15] opened 2019-11-02 15:20 UTC
When updating to `1.0.3` docs are still being built but process exits with an error:

```
Error: The plugin /tmp/test/node_modules/typedoc-neo-theme could not be loaded.

Error: Cannot find module '@gerrit0/typedoc/dist/lib/converter/components'
Require stack:
- /tmp/test/node_modules/typedoc-neo-theme/bin/default/plugin.js
- /tmp/test/node_modules/typedoc-neo-theme/index.js
- /tmp/test/node_modules/typedoc/dist/lib/utils/plugins.js
- /tmp/test/node_modules/typedoc/dist/lib/utils/index.js
- /tmp/test/node_modules/typedoc/dist/lib/serialization/components.js
- /tmp/test/node_modules/typedoc/dist/lib/serialization/index.js
- /tmp/test/node_modules/typedoc/dist/lib/application.js
- /tmp/test/node_modules/typedoc/dist/lib/cli.js
- /tmp/test/node_modules/typedoc/bin/typedoc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /tmp/test/node_modules/typedoc-neo-theme/bin/default/plugin.js:33:26
    at /tmp/test/node_modules/typedoc-neo-theme/bin/default/plugin.js:9:17
    at Object.<anonymous> (/tmp/test/node_modules/typedoc-neo-theme/bin/default/plugin.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)

```

I've set up a minimal repo for showcase [here](https://github.com/Floppy012/typedoc-neo-minimal).

**Comment by Fleker** [comment] 2019-11-04 16:21
Duplicate of #10

**Closed** 2019-11-06 22:52 UTC
Labels: duplicate
